# ==============================================================================
#  Render Blueprint: EcoMemories Smart Kiosk Web Service & PostgreSQL Database
# ==============================================================================
services:
  - type: web
    name: ecomemories-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: APP_NAME
        value: EcoMemories
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: base64:nAeHeuHEuJsP1gmw4jgCfrBbgHSjDAN7LhAa2urZXOM=
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: ecomemories-db
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: ecomemories-db
          property: connectionString
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file

databases:
  - name: ecomemories-db
    plan: free
    databaseName: ecophotobooth_website
